# .github/workflows/keepalive.yml
name: Keepalive
on:
  schedule:
    - cron: "0 0 1 * *" # Run on the 1st day of every month at midnight UTC
  workflow_dispatch: # Allow manual triggers

jobs:
  keepalive:
    runs-on: ubuntu-latest
    steps:
      - name: Keep workflow active
        run: echo "Keeping repository active - $(date)"
